### ISSUE TITLE
New York City has more cases than New York.

### ISSUE THREAD

**Issue by mrdrozdov** [octopicorn/covid19-charts#13]
Seems like some of the state data is inaccurate before 3/10/2020. For example, New York City has more than New York (New York is shown to have 0).

Other states might have the same problem.

Not sure what is the right fix (for example, could use the county data to make up for the missing state data, but not sure if that is okay).
<img width="1792" alt="Screen Shot 2020-03-29 at 4 26 02 PM" src="https://user-images.githubusercontent.com/1575034/77859906-0641b480-71da-11ea-934a-19104ddd3206.png">

**Comment by mrdrozdov** [comment]
It's sort of minor issue at first glance. Thank you for the great tool!

**Comment by octopicorn** [comment]
Thank you for reporting this issue. I'm taking a look.

**Comment by mrdrozdov** [comment]
No problem. I wonder if the states only includes data for when there was more than 100 cases?

**Comment by octopicorn** [comment]
The state data before 3/23 was all pulled from the V1 file. This is the file they were publishing in the JH CSSE repo until 3/23. Then without warning they stopped supporting it and removed it.

Now the daily global report has only US as a single row, no states. And the daily report files they also release every day have only counties, not states as a whole. So I have to tally up the counties.

I'll look back to see what is going in the V1 file.

**Comment by octopicorn** [comment]
It is line 101 in this file:
https://github.com/octopicorn/covid19-charts/blob/master/downloads/Confirmed_v1.csv#L101

yes looks like the first reprted was just on 3/10. It must just have been a reporting issue, like that's the first time CSSE got a confirmed count from state of NY. Or maybe they just got testing kits or started testing around that time.

**Comment by octopicorn** [comment]
There is also a dataset release by New York Times as of Friday.
I'm not using it right now, because it's
1. in a totally different format
2. they are not clear about how often they will be updating it

but it may be worth going back to fill in those numbers, or at least cross reference the time period around 3/10 and see if NYT released better data for their state.

**Comment by octopicorn** [comment]
Yes, confirmed - NYT dataset has it.
Not sure if it's worth it to go back and fix this for all 50 states. Most of them will have zeros, since it was only five or six states that even had major cases back in early March.

You can search for "New York" in this dataset:
https://github.com/nytimes/covid-19-data/blob/master/us-states.csv

On the positive side, both datasets line up to the same confirmed count of 173 on 3/10/20, so they're not far off from each other hopefully, though i expect there will be some differences

**Comment by mrdrozdov** [comment]
Thanks for the info!

**Comment by octopicorn** [comment]
Since the V1 dataset I have from JH is no longer officially supported, and is strictly historical, I feel fine just making edits to it to update New York state specifically. We can do others as needed. Also will be needed to update the README to give attribution to NYT dataset as source.

**Comment by octopicorn** [comment]
OK done!
https://github.com/octopicorn/covid19-charts/pull/20
