### ISSUE TITLE
add cache busting to timeseries and menu JSON files so hard-refresh in browser is not needed

### ISSUE THREAD

**Issue by JordanAsh** [octopicorn/covid19-charts#45]
Right now, the "US Counties" box only includes an item called ", Recovered".  Could someone take a look?

**Comment by octopicorn** [comment]
This was a momentary issue yesterday, because the daily update from JH was malformed and was missing all US county data.

Please try a hard refresh in your browser (or `git pull` if you're running locally)

This site is purely static, and there is no cache buster in there yet to force udpate of javascript code and json files on refresh. I will keep this issue open to implement cache busting for the `timeseries.json` files. Thank you.
