### ISSUE TITLE
US counties no longer being reported?

### ISSUE THREAD

**Issue by PaulJWright** [octopicorn/covid19-charts#68]
It seems that US counties are no longer being reported.

![Screenshot 2020-04-24 at 17 17 52](https://user-images.githubusercontent.com/8172222/80266199-90513180-864f-11ea-9e1d-1e37744a45db.png)

**Comment by octopicorn** [comment]
Thank you for reporting @PaulJWright !
Seems like JH decided to rename their repo without warning :)
All good now

**Comment by octopicorn** [comment]
Their repo was renamed from `2019-nCoV` to `COVID-19`

**Comment by shashank-s** [comment]
County data missing again on May 21, 2020 or more like a week or 10 days ago after missing and reappearing briefly.

**Comment by octopicorn** [comment]
@shashank-s thank you for reporting this
 
the site is set to auto update the day's latest data form JH CSSE every day a few minutes after 5pm Pacific (which is 00:00:00 in GMT)

looks like JH has changed their autoupdates to happen at 7p instead of 5p, so the auto updates for past several days we returning empty.

I fixed this up to may 20, but today's data (May 21) has not been published yet

you can see this here:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

**Comment by octopicorn** [comment]
@shashank-s 
this is resolved by https://github.com/octopicorn/covid19-charts/pull/72
thank you
